build(contracts): alt &  lattice
HelheimLabs/autochessia pull request #143
Opened 2023-08-25 16:49 UTC by aLIEzsss4

The alt network cannot function properly because requesting a gaslimit of 0 results in errors, but lattice works. The .env needs to be modified with VITE_CHAIN_ID=4242

@noyyyy

2023-08-25 17:02 UTC, noyyyy requested changes
It's not contract address problem. It's due to viem like

```
TransactionExecutionError: An internal error was received.

URL: https://flashlayer.alt.technology/autochessia7806fd60
Request body: {"method":"eth_estimateGas","params":[{"from":"0x5Bf8C4Fb557e1C7F24c74db67E3d940B8c16904c","data":"0x00ac498a310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000","maxFeePerGas":"0x59682f00","maxPriorityFeePerGas":"0x59682f00","nonce":"0x0","to":"0x6eea611D1e9eA24e8Ce2Ad5aD5f1404B5Fe6ab6E"}]}
 
Estimate Gas Arguments:
  from:                  0x5Bf8C4Fb557e1C7F24c74db67E3d940B8c16904c
  to:                    0x6eea611D1e9eA24e8Ce2Ad5aD5f1404B5Fe6ab6E
  data:                  0x00ac498a310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000
  maxFeePerGas:          1.5 gwei
  maxPriorityFeePerGas:  1.5 gwei
  nonce:                 0
 
Request Arguments:
  from:   0x5Bf8C4Fb557e1C7F24c74db67E3d940B8c16904c
  to:     0x6eea611D1e9eA24e8Ce2Ad5aD5f1404B5Fe6ab6E
  data:   0x00ac498a310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000
  nonce:  0

Details: gas required exceeds allowance 0
Version: viem@1.5.4
```

Can you have a play on your pc on altlayer?

2023-08-25 17:02 UTC, noyyyy commented on packages/client/src/App.tsx
> -      <div className="absolute bottom-20 right-4 grid">
why buttom rather than top

2023-08-25 17:02 UTC, noyyyy commented on packages/contracts/worlds.json
> -    "blockNumber": 3896268
You don't need to deploy it on altlayer manually as github action will do it

2023-08-25 17:04 UTC, noyyyy commented
> The alt network cannot function properly because requesting a gaslimit of 0 results in errors, but lattice works. The .env needs to be modified with VITE_CHAIN_ID=4242
> 
> @noyyyy

It's better to switch like

```
  const chainId = Number(params.get("chainId") || latticeTestnet.id);
```

Do you understand my old version?

2023-08-25 17:50 UTC, aLIEzsss4 commented on packages/client/src/App.tsx
> -      <div className="absolute bottom-20 right-4 grid">
It will cover up the coin.

2023-08-25 17:53 UTC, noyyyy commented on packages/client/src/App.tsx
> -      <div className="absolute bottom-20 right-4 grid">
It's fine

2023-08-26 11:54 UTC, noyyyy reviewed
LGTM

2023-08-26 11:54 UTC, noyyyy approved these changes

2023-08-26 11:55 UTC, merged