upgrade(cli): MUD Version 2.0.0-next.8
HelheimLabs/autochessia pull request #182
Opened 2023-09-14 18:38 UTC by aLIEzsss4

2023-09-14 18:51 UTC, aLIEzsss4 commented
The contracts have been split for now, further optimization is needed.

2023-09-15 05:41 UTC, noyyyy approved these changes

2023-09-15 05:41 UTC, noyyyy commented on package.json
> -    "prepare": "(forge --version || pnpm foundry:up);pnpm simple-git-hooks",
why remove `simple-git-hooks`. It's used for code auto format

2023-09-15 05:41 UTC, noyyyy commented on packages/contracts/remappings.txt
> +forge-std/=./node_modules/forge-std/src/
don't use `forge-std`, `ds-test`. Use forge install to install them

2023-09-15 05:41 UTC, noyyyy commented on packages/indexer/Dockerfile
> +    git checkout 1efccab99fbb5b16a5e7980683f74f3ad8ec4e21 && \
Did indexer code change? Did you deploy and test it?

2023-09-15 05:41 UTC, noyyyy requested changes
see above

2023-09-15 05:57 UTC, noyyyy commented
![image](https://github.com/HelheimLabs/autochessia/assets/59097122/cace960d-59b7-498e-9504-10e3285c527d)
https://discord.com/channels/865335009915961364/1151938472131694745/1152120768310820895

2023-09-15 10:41 UTC, aLIEzsss4 commented
This MUD upgrade includes development versions of forge-std and ds-test dependencies. I think we should synchronize with them. 

https://github.com/latticexyz/mud/blob/5150544354816949ab3d47950df7fc67ded797a7/examples/minimal/packages/contracts/package.json#L27

or 
```
forge-std/=lib/forge-std/src/
ds-test/=lib/ds-test/src/
@latticexyz/=node_modules/@latticexyz/
@openzeppelin-contracts=lib/openzeppelin-contracts/contracts
cement/=lib/cement/contracts/
```

2023-09-15 10:46 UTC, noyyyy commented
> This MUD upgrade includes development versions of forge-std and ds-test dependencies. I think we should synchronize with them.
> 
> https://github.com/latticexyz/mud/blob/5150544354816949ab3d47950df7fc67ded797a7/examples/minimal/packages/contracts/package.json#L27
> 
> or
> 
> ```
> forge-std/=lib/forge-std/src/
> ds-test/=lib/ds-test/src/
> @latticexyz/=node_modules/@latticexyz/
> @openzeppelin-contracts=lib/openzeppelin-contracts/contracts
> cement/=lib/cement/contracts/
> ```

If you use ssh clone. It will generate lock which cannot be used directly in github action. 

If you have used foundry, foundry project mainly use forge install to generate git submodule. By using submodule, you can also assign a commit hash.

Also the `forge-std` and `ds-test` are not maintained by lattice. Their api is stable. It usually doesn't matter if you use a different newer version.

2023-09-16 15:54 UTC, aLIEzsss4 commented
> > This MUD upgrade includes development versions of forge-std and ds-test dependencies. I think we should synchronize with them.
> > https://github.com/latticexyz/mud/blob/5150544354816949ab3d47950df7fc67ded797a7/examples/minimal/packages/contracts/package.json#L27
> > or
> > ```
> > forge-std/=lib/forge-std/src/
> > ds-test/=lib/ds-test/src/
> > @latticexyz/=node_modules/@latticexyz/
> > @openzeppelin-contracts=lib/openzeppelin-contracts/contracts
> > cement/=lib/cement/contracts/
> > ```
> 
> If you use ssh clone. It will generate lock which cannot be used directly in github action.
> 
> If you have used foundry, foundry project mainly use forge install to generate git submodule. By using submodule, you can also assign a commit hash.
> 
> Also the `forge-std` and `ds-test` are not maintained by lattice. Their api is stable. It usually doesn't matter if you use a different newer version.

fix

2023-09-21 04:22 UTC, noyyyy requested changes
I will modify indexer things in another pr. Discard these to avoid conflict.

2023-09-21 04:22 UTC, noyyyy commented on packages/indexer/fly.alt.toml
> -START_BLOCK = 702262
just discard this change.

2023-09-21 04:22 UTC, noyyyy commented on packages/indexer/fly.lattice.toml
> -START_BLOCK = 23288565
just discard this change.

2023-09-22 18:33 UTC, aLIEzsss4 commented
> I will modify indexer things in another pr. Discard these to avoid conflict.

fix

2023-09-23 17:02 UTC, noyyyy approved these changes
LGTM

2023-09-23 17:09 UTC, noyyyy commented
Let's work together when you're free @aLIEzsss4. We need another indexer change pr to be merged at the same time

2023-09-23 17:31 UTC, noyyyy commented
See #184, but it's wip.

2023-09-24 11:29 UTC, merged