refactor: rm inventory emptyIds
HelheimLabs/autochessia pull request #69
Opened 2023-08-02 16:55 UTC by noyyyy

2023-08-03 06:02 UTC, ClaudeZsb commented on packages/contracts/src/library/Utils.sol
> +    for (uint256 i = 0; i < GameConfig.getInventorySlotNum(); i++) {
I suggest that 
- Get out all values in inventory once. We now have 7 slots in inventory. This costs less gas than 2 times of gas for reading one slot. 
- Create a new local variable for inventory slot num. Set its value to length of inventory you got. Use it in the loop and save gas of reading one slot(`GameConfig.getInventorySlotNum()`) for each iteration.

2023-08-03 06:04 UTC, ClaudeZsb commented on packages/contracts/src/library/Utils.sol
> +    for (uint256 i = 0; i < GameConfig.getInventorySlotNum(); i++) {
Why not keep on writing loop with `unchecked increment of i`. It's cheaper than `++i` which is cheaper than `i++`.

2023-08-03 06:08 UTC, ClaudeZsb commented on packages/contracts/src/systems/PlaceSystem.sol
> +  function placeBackInventory(uint256 herosIndex) public onlyWhenGamePreparing returns (uint256 invIdx) {
What about adding a new input param `invIndex` which represents the index of slot in inventory where player wants to place the hero? I've seen it in a previous pr and think it's good.

2023-08-03 06:44 UTC, noyyyy commented on packages/contracts/src/systems/PlaceSystem.sol
> +  function placeBackInventory(uint256 herosIndex) public onlyWhenGamePreparing returns (uint256 invIdx) {
> What about adding a new input param `invIndex` which represents the index of slot in inventory where player wants to place the hero? I've seen it in a previous pr and think it's good.

There is a function `placeBackInventoryAndSwap` to do this, for backward compatibility. Will break this compatibility in another pr.

2023-08-03 06:45 UTC, noyyyy commented on packages/contracts/src/library/Utils.sol
> +    for (uint256 i = 0; i < GameConfig.getInventorySlotNum(); i++) {
u r right. will modify.

2023-08-03 17:16 UTC, noyyyy commented
@ClaudeZsb please review again

2023-08-04 07:45 UTC, ClaudeZsb requested changes
At `ShopSystem.sol:36`, getting an item from a dynamic array in mud store with an index larger than the array length will probably not produce a revert. And the value you got is not predictable.  So better remove a hero in altar in the same way as removing a hero in inventory.

2023-08-04 07:45 UTC, ClaudeZsb commented on packages/contracts/src/library/Utils.sol
> +    uint256 length = GameConfig.getInventorySlotNum(0);
```
uint256 length = inv.length;
```

2023-08-04 07:54 UTC, ClaudeZsb commented on packages/contracts/src/library/Utils.sol
>    function removeHeroByIndex(address _player, uint256 _index) internal returns (HeroData memory hero) {
Those two funcs `removeHeroByIndex` and `deleteHeroByIndex` do the same thing but in different ways. @aLIEzsss4 
Do we need to maintain the order of hero in `Player.heroes` array?  If the answer is yes, then we keep `removeHeroByIndex` and remove the other one. If not, do the reverse.

2023-08-04 20:13 UTC, noyyyy commented on packages/contracts/src/library/Utils.sol
> +    uint256 length = GameConfig.getInventorySlotNum(0);
> ```
> uint256 length = inv.length;
> ```

Fixed

2023-08-04 20:17 UTC, noyyyy commented
> At `ShopSystem.sol:36`, getting an item from a dynamic array in mud store with an index larger than the array length will probably not produce a revert. And the value you got is not predictable. So better remove a hero in altar in the same way as removing a hero in inventory.

If index is larger than length -1, the value will be zero, and we have zero check to make this revert.
`require(creatureId != 0, "empty hero altar slot");`

2023-08-04 20:23 UTC, noyyyy commented on packages/contracts/src/library/Utils.sol
>    function removeHeroByIndex(address _player, uint256 _index) internal returns (HeroData memory hero) {
> `removeHeroByIndex`

No. They are not the same. `removeHeroByIndex` delete hero in heros array, `deleteHeroByIndex` delete hero in inventory array.

2023-08-04 20:27 UTC, noyyyy commented on packages/contracts/src/library/Utils.sol
>    function removeHeroByIndex(address _player, uint256 _index) internal returns (HeroData memory hero) {
> Those two funcs `removeHeroByIndex` and `deleteHeroByIndex` do the same thing but in different ways. @aLIEzsss4 Do we need to maintain the order of hero in `Player.heroes` array? If the answer is yes, then we keep `removeHeroByIndex` and remove the other one. If not, do the reverse.

`removeHeroByIndex` is not used. So I think @aLIEzsss4 has make his decision.

2023-08-05 03:48 UTC, ClaudeZsb commented
> > At `ShopSystem.sol:36`, getting an item from a dynamic array in mud store with an index larger than the array length will probably not produce a revert. And the value you got is not predictable. So better remove a hero in altar in the same way as removing a hero in inventory.
> 
> If index is larger than length -1, the value will be zero, and we have zero check to make this revert. `require(creatureId != 0, "empty hero altar slot");`

The reason why I said ***The value you got is not predictable*** is that the index(`uint256`) could be extremely large. And `Mud` do not check the index for us. They just calculate and read from the start to the end slot number. In the worst case, a malicious player could read at most next `1/4 * type(uint256).max` slots and we have no idea now what will be stored there. So I recommend that we do something to avoid any reading overflowed into other table or dynamic field.

2023-08-05 09:36 UTC, noyyyy commented
> 

I see. But this will not happen since we set inventory to a fixed length array when refresh altar.

https://github.com/HelheimLabs/autochessia/blob/f5fe8a8f2d3f6c93c5b5e3abe96ef1f0a64be936/packages/contracts/src/systems/RefreshHeroesSystem.sol#L14-L56


If the index is larger than array length. contract will revert. We can add a test to make sure of it.

2023-08-05 09:36 UTC, noyyyy commented
> > > At `ShopSystem.sol:36`, getting an item from a dynamic array in mud store with an index larger than the array length will probably not produce a revert. And the value you got is not predictable. So better remove a hero in altar in the same way as removing a hero in inventory.
> > 
> > 
> > If index is larger than length -1, the value will be zero, and we have zero check to make this revert. `require(creatureId != 0, "empty hero altar slot");`
> 
> The reason why I said _**The value you got is not predictable**_ is that the index(`uint256`) could be extremely large. And `Mud` do not check the index for us. They just calculate and read from the start to the end slot number. In the worst case, a malicious player could read at most next `1/4 * type(uint256).max` slots and we have no idea now what will be stored there. So I recommend that we do something to avoid any reading overflowed into other table or dynamic field.


I see. But this will not happen since we set inventory to a fixed length array when refresh altar.

https://github.com/HelheimLabs/autochessia/blob/f5fe8a8f2d3f6c93c5b5e3abe96ef1f0a64be936/packages/contracts/src/systems/RefreshHeroesSystem.sol#L14-L56


If the index is larger than array length. contract will revert. We can add a test to make sure of it.

2023-08-05 14:01 UTC, noyyyy commented
> The reason why I said _**The value you got is not predictable**_ is that the index(`uint256`) could be extremely large. And `Mud` do not check the index for us. They just calculate and read from the start to the end slot number. In the worst case, a malicious player could read at most next `1/4 * type(uint256).max` slots and we have no idea now what will be stored there. So I recommend that we do something to avoid any reading overflowed into other table or dynamic field.

Got it. u r right.

2023-08-06 03:08 UTC, ClaudeZsb approved these changes

2023-08-06 03:09 UTC, merged